# 0x05-python-exceptions

## Python - Exceptions
### 0-safe_print_list.py
* Function prints `x` elements of a list
* Prototype: `def safe_print_list(my_list=[], x=0):`
* Return: number of elements printed

### 1-safe_print_integer.py
* Function prints an integer with `"{:d}".format()`
* Prototype: `def safe_print_integer(value):`
* Return: `True` if value is printed correctly, `False` otherwise

### 2-safe_print_list_integers.py
* Function prints the first `x` elements that are integers in a list
* Prototype: `def safe_print_list_integers(my_list=[], x=0):`
* Return: number of integers printed

### 3-safe_print_division.py
* Function divides 2 integers and prints the result
* Prototype: `def safe_print_division(a, b):`
* Return: result of division, `None` if divide by 0

### 4-list_division.py
* Function divides element by element from two lists
* Prototype: `def list_division(my_list_1, my_list_2, list_length):`
* Return: new list of length `list_length` with result of divisions

### 5-raise_exception.py
* Function raises a type exception
* Prototype: `def raise_exception():`

### 6-raise_exception_msg.py
* Function raises a name exception with a message
* Prototype: `def raise_exception_msg(message=""):`

### 100-safe_print_integer_err.py
* Function prints an integer
* Prototype: `def safe_print_integer_err(value):`
* Return: `True` if value is printed correctly, `False` otherwise
